// Drift guard for docs/compliance/regulated-adoption.md (ADR-0031).
//
// The vendor sheet is a document derived from real facts about this repository. A document
// can silently go stale. This test makes that impossible: every verifiable fact the sheet
// asserts to a regulated buyer is checked here. If the posture changes — a control removed,
// an action un-pinned, a long-lived secret introduced, the licence changed, the SBOM/provenance
// step deleted — a test breaks and CI reddens. So the fix is forced: restore the fact, or update
// the sheet. The document can never lie to an auditor without turning the gate red first.
//
// This is the runward principle applied to runward's own governance: the maintainer decides,
// but a deterministic gate guarantees the claim and the reality do not drift apart.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const read = (p) => readFileSync(join(ROOT, p), "utf8");
const has = (p) => existsSync(join(ROOT, p));
const workflows = () => readdirSync(join(ROOT, ".github/workflows")).filter((f) => /\.ya?ml$/.test(f));

test("posture: the governance / health files the sheet relies on exist", () => {
  for (const f of [
    "SECURITY.md", ".github/CODEOWNERS", "GOVERNANCE.md", "CONTRIBUTING.md",
    ".github/dependabot.yml", ".github/workflows/scorecard.yml",
    "LICENSE", "NOTICE.md", "CHANGELOG.md", "package-lock.json",
    "docs/compliance/regulated-adoption.md", "docs/compliance/oscal-ingest.md",
    "test/oscal-ingest.py",
  ]) assert.ok(has(f), `missing ${f} — claimed by regulated-adoption.md`);
  assert.ok(readdirSync(join(ROOT, "docs/adr")).some((f) => /^ADR-0031/.test(f)), "ADR-0031 present");
});

test("posture: release wires provenance + an attested SBOM bound to the published tarball", () => {
  const rel = read(".github/workflows/release.yml");
  assert.match(rel, /npm publish[^\n]*--provenance/, "npm --provenance (Sigstore signature)");
  assert.match(rel, /sbom-action@[0-9a-f]{40}/, "SBOM generated by a SHA-pinned action");
  // actions/attest (attest-sbom's successor) attests the SBOM when sbom-path is set;
  // both matches together keep the guarded property: SBOM SLSA-attested, SHA-pinned.
  assert.match(rel, /actions\/attest@[0-9a-f]{40}/, "SBOM SLSA-attested (SHA-pinned action)");
  assert.match(rel, /sbom-path:/, "the attestation is bound to the SBOM (sbom-path input)");
  assert.match(rel, /npm publish "\$TARBALL"/, "publishes the packed tarball itself (attested == published)");
});

test("posture: CI runs core tests network-isolated, gates runward, and tracks SBOM drift", () => {
  const ci = read(".github/workflows/ci.yml");
  assert.match(ci, /unshare -n/, "network-isolated core tests (structural zero-network)");
  assert.match(ci, /check --strict/, "self-gate as a required check");
  assert.match(ci, /sbom-action@[0-9a-f]{40}/, "SBOM on every push/PR (drift), SHA-pinned");
  assert.match(ci, /compliance-trestle/, "OSCAL ingested by a third-party tool (compliance-trestle) in CI");
});

test("posture: dated external facts are watched out-of-band (ADR-0032)", () => {
  assert.ok(has(".github/workflows/watch-external-facts.yml"), "the external-facts watch workflow exists");
  const wf = read(".github/workflows/watch-external-facts.yml");
  assert.match(wf, /schedule:/, "the watch runs on a schedule, outside the gate");
  assert.match(wf, /usnistgov\/OSCAL/, "it checks the pinned OSCAL version against NIST releases");
  assert.match(wf, /reviewBy/, "it checks the regime reviewBy dates");
  // The claim the watch protects: at least one shipped regime carries a reviewBy re-check date.
  const regimes = readdirSync(join(ROOT, "regimes")).filter((f) => f.endsWith(".json"));
  assert.ok(
    regimes.some((f) => /"reviewBy"\s*:/.test(read(join("regimes", f)))),
    "at least one regimes/*.json carries a reviewBy date for the watch to track",
  );
});

test("posture: every workflow action is pinned by commit SHA (no mutable tags)", () => {
  for (const wf of workflows()) {
    for (const m of read(join(".github/workflows", wf)).matchAll(/^\s*(?:-\s*)?uses:\s*(\S+)/gm)) {
      assert.match(m[1], /@[0-9a-f]{40}$/, `${wf}: "${m[1]}" is not pinned by a 40-char commit SHA`);
    }
  }
});

test("posture: no long-lived secrets in any workflow (OIDC trusted publishing only)", () => {
  for (const wf of workflows()) {
    const refs = [...read(join(".github/workflows", wf)).matchAll(/\$\{\{\s*secrets\.([A-Za-z0-9_]+)/g)].map((m) => m[1]);
    assert.deepEqual(refs, [], `${wf}: references long-lived secret(s) [${refs.join(", ")}] — the sheet claims none`);
  }
});

test("posture: licences match the sheet — MIT tooling, CC BY-ND doctrine", () => {
  assert.match(read("LICENSE"), /\bMIT\b/, "MIT tooling licence");
  assert.match(read("NOTICE.md"), /BY-ND/, "CC BY-ND doctrine notice");
});
